services:
    gothick.phpbb-ext-akismet.controller:
        class: gothick\phpbb-ext-akismet\controller\main
        arguments:
             - @config
	     - @controller.helper
	     - @template
	     - @user
