services:
  gothick.akismet.controller:
    class: gothick\akismet\controller\main
    arguments:
      - @config
      - @controller.helper
      - @template
      - @user
  gothick.akismet.listener:
    class: gothick\akismet\event\main_listener
    arguments:
      - @controller.helper
      - @template
    tags:
      - { name: event.listener }
